[versions]
jacksonVersion = "2.21.0"
dotenvVersion = "6.5.1"
log4j2-version = "2.25.3"
kotlinLoggingVersion = "8.0.01"
exposedVersion = "1.0.0"
mariadbVersion = "3.5.7"
sqliteVersion = "3.51.2.0"

[libraries]
jacksonBom = { group = "com.fasterxml.jackson", name = "jackson-bom", version.ref = "jacksonVersion"}
jacksonKotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin" }
jacksonYaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml" }
dotenvKotlin = { group = "io.github.cdimascio", name = "dotenv-kotlin", version.ref = "dotenvVersion" }
kotlinLogging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlinLoggingVersion" }
log4j2Bom = { group = "org.apache.logging.log4j", name = "log4j-bom", version.ref = "log4j2-version"}
log4j2-core = { group = "org.apache.logging.log4j", name = "log4j-core" }
log4j2-slf4j = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl" }
log4j2-json = { group = "org.apache.logging.log4j", name = "log4j-layout-template-json" }
exposedCore = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposedVersion" }
exposedJdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version.ref = "exposedVersion" }
exposedJavaTime = { group = "org.jetbrains.exposed", name = "exposed-java-time", version.ref = "exposedVersion" }
mariadb = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "mariadbVersion" }
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqliteVersion" }


[bundles]
jackson = ["jacksonKotlin", "jacksonYaml"]
logging = ["kotlinLogging", "log4j2-core", "log4j2-slf4j", "log4j2-json"]
exposed = ["exposedCore", "exposedJdbc", "exposedJavaTime"]

[plugins]
